package com.myspace.demo_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanOutcome implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String outcome;

	public LoanOutcome() {
	}

	public java.lang.String getOutcome() {
		return this.outcome;
	}

	public void setOutcome(java.lang.String outcome) {
		this.outcome = outcome;
	}

	public LoanOutcome(java.lang.String outcome) {
		this.outcome = outcome;
	}

}